version: "3.8"

services:
  clickhouse:
    image: docker.io/bitnami/clickhouse:25
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_ADMIN_USER=admin
      - CLICKHOUSE_ADMIN_PASSWORD=admin
    ports:
      - "8123:8123" # HTTP Interface
      - "9000:9000" # Native TCP Interface
    volumes:
      - clickhouse_data:/bitnami/clickhouse

  dremio:
    image: dremio/dremio-oss:latest
    ports:
      - "9047:9047" # Dremio Web UI
      - "31010:31010" # Dremio JDBC
    environment:
      - DREMIO_DATADIR=/opt/dremio/data
      - DREMIO_LOGDIR=/opt/dremio/log
      - DREMIO_ADMIN_USERNAME=admin
      - DREMIO_ADMIN_PASSWORD=admin
      - DREMIO_DISABLE_SIGN_UP=true
      - DREMIO_S3_ENABLED=true
      - DREMIO_S3_ACCESS_KEY=your-s3-access-key
      - DREMIO_S3_SECRET_KEY=your-s3-secret-key
      - DREMIO_S3_BUCKET=your-s3-bucket-name
      - DREMIO_ICEBERG_ENABLED=true
      - DREMIO_METADATA_STORAGE_TYPE=postgresql
      - DREMIO_METADATA_STORAGE_URI=jdbc:postgresql://postgres:5432/dremio
      - DREMIO_METADATA_STORAGE_USERNAME=dremio
      - DREMIO_METADATA_STORAGE_PASSWORD=dremio
    volumes:
      - dremio_data:/opt/dremio/data
      - dremio_logs:/opt/dremio/log
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=trino
    ports:
      - "5432:5432" # PostgreSQL Port
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    restart: always
    ports:
      - "5521:5521"
    environment:
      VITE_CLICKHOUSE_URL: "http://localhost:8123"
      VITE_CLICKHOUSE_USER: "admin"
      VITE_CLICKHOUSE_PASS: "admin"
    depends_on:
      - clickhouse

  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    build: spark/
    networks:
      iceberg_net:
    depends_on:
      - rest
      - minio
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001
  rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "

volumes:
  clickhouse_data:
    driver: local
  dremio_data:
    driver: local
  dremio_logs:
    driver: local
  postgres_data:
    driver: local

networks:
  iceberg_net:
